name: Build, Test and Publish

on:
  push:
    branches: [ suwpb ]

env:
  CONFIGURATION: Release
  SOLUTION_FILE_PATH: ./src/Localization.SqlLocalizer/Localization.SqlLocalizer.sln
  NUGET_FILE_PATH: ./src/Localization.SqlLocalizer/bin/Release/*.nupkg

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore "${{ env.SOLUTION_FILE_PATH }}"

      - name: Build
        run: dotnet build "${{ env.SOLUTION_FILE_PATH }}" -c "${{ env.CONFIGURATION }}" --no-restore

      - name: Publish NuGet package
        shell: bash
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          SOURCE_NUGET: https://api.nuget.org/v3/index.json
        run: dotnet nuget push "${{ env.NUGET_FILE_PATH }}" --source $SOURCE_NUGET --api-key $NUGET_API_KEY --skip-duplicate